/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GradesRouteImport } from './routes/grades'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as CourseCourseIdRouteImport } from './routes/course.$courseId'
import { Route as QCodeRouteImport } from './routes/q.$code'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCalendarTokenRouteImport } from './routes/api/calendar/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesRoute = GradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const QCodeRoute = QCodeRouteImport.update({
  id: '/q/$code',
  path: '/q/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarTokenRoute = ApiCalendarTokenRouteImport.update({
  id: '/api/calendar/$token',
  path: '/api/calendar/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grades': typeof GradesRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/practice': typeof PracticeRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/q/$code': typeof QCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/calendar/$token': typeof ApiCalendarTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grades': typeof GradesRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/practice': typeof PracticeRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/q/$code': typeof QCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/calendar/$token': typeof ApiCalendarTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/grades': typeof GradesRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/practice': typeof PracticeRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/q/$code': typeof QCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/calendar/$token': typeof ApiCalendarTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/grades'
    | '/login'
    | '/plan'
    | '/practice'
    | '/course/$courseId'
    | '/q/$code'
    | '/api/auth/$'
    | '/api/calendar/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/grades'
    | '/login'
    | '/plan'
    | '/practice'
    | '/course/$courseId'
    | '/q/$code'
    | '/api/auth/$'
    | '/api/calendar/$token'
  id:
    | '__root__'
    | '/'
    | '/grades'
    | '/login'
    | '/plan'
    | '/practice'
    | '/course/$courseId'
    | '/q/$code'
    | '/api/auth/$'
    | '/api/calendar/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GradesRoute: typeof GradesRoute
  LoginRoute: typeof LoginRoute
  PlanRoute: typeof PlanRoute
  PracticeRoute: typeof PracticeRoute
  CourseCourseIdRoute: typeof CourseCourseIdRoute
  QCodeRoute: typeof QCodeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCalendarTokenRoute: typeof ApiCalendarTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades': {
      id: '/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof GradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$code': {
      id: '/q/$code'
      path: '/q/$code'
      fullPath: '/q/$code'
      preLoaderRoute: typeof QCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/$token': {
      id: '/api/calendar/$token'
      path: '/api/calendar/$token'
      fullPath: '/api/calendar/$token'
      preLoaderRoute: typeof ApiCalendarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GradesRoute: GradesRoute,
  LoginRoute: LoginRoute,
  PlanRoute: PlanRoute,
  PracticeRoute: PracticeRoute,
  CourseCourseIdRoute: CourseCourseIdRoute,
  QCodeRoute: QCodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCalendarTokenRoute: ApiCalendarTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
